### PR TITLE
Add movable_value

### PR DESCRIPTION
**Pull request by miscco**

### CODE REVIEW

**Comment by dietmarkuehl** [comment]
It seems, gcc needs to be directed more explicitly than, e.g., clang, at another header when trying to extend the content of `<functional>`. Applying the following change causes gcc to compile the code (please let me know if I should push the change and I'll do so):

    diff --git a/std-headers/functional b/std-headers/functional
    index 76909a7..c1be113 100644
    --- a/std-headers/functional
    +++ b/std-headers/functional
    @@ -28,7 +28,11 @@
     
     // ----------------------------------------------------------------------------
     
    -#include <functional>
    +#if defined(__GNUC__)
    +#    include_next <functional>
    +#else
    +#    include <functional>
    +#endif
    #include <functional.hpp>
     
    // ----------------------------------------------------------------------------

**Review by dietmarkuehl — CHANGES_REQUESTED** [review]
[P2300r4](http://wg21.link/P2300r4) does use `decay_t` instead `remove_cvref_t`. I do believe for the relevant definitions should be in sync, i.e., either P2300 gets update or the implementation.

**Comment by miscco** [comment]
> [P2300r4](http://wg21.link/P2300r4) does use `decay_t` instead `remove_cvref_t`. I do believe for the relevant definitions should be in sync, i.e., either P2300 gets update or the implementation.

Yeah that was me being sloppy, sorry

**Review by dietmarkuehl — APPROVED** [review]
LGTM

**Pull request merged**
